apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: theofaedo/eduplanner_back_repository:arm64
          ports: # eduplanner_back_repository:arm64
            - containerPort: 8080
          env: 
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/data"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            #- name: SERVER_PORT
            #  value: 

            
