apiVersion: v1
kind: Service
metadata:
  name: planner-service
spec:
  selector:
    app: planner
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      #nodePort: 30080
  type: ClusterIP