apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pc-volume-clain
  labels: 
    app: postgres
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
